# Generated by Django 3.1.4 on 2021-01-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptodata',
            name='prices',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptodata',
            name='time_and_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
